name = "EscapeBot"
license = "Apache-2.0"
licenselink = "https://github.com/asheinking/tailbliss/blob/main/LICENSE"
description = "EscapeBot is a multi-layered tool for forecasting financial performance and identifying investment insights. Features include sector-level analysis, earnings transcripts evaluation, valuation models, and market pattern recognition."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/asheinking/tailbliss"

# If you have a running demo of the theme.
demosite = "https://about.escape-bot.com/"

tags = ["finance", "investing", "analytics", "forecasting", "machine-learning", "financial-analysis", "portfolio", "trading", "stocks", "quant", "fundamental-analysis" ]
features = ["sector-analysis", "earnings-analysis", "valuation-models", "pattern-recognition", "community", "research"]

min_version = "0.114.0"

# If the theme has a single author
[author]
    name = "EscapeBot Team"
    homepage = "https://github.com/asheinking/tailbliss"

# If porting an existing theme
[original]
  name = "Hugo-Tailwind-3.1"
  author = "4044ever"
  homepage = "https://github.com/4044ever"
  repo = "https://github.com/4044ever/Hugo-Tailwind-3.1"